project:
  type: website

website:
  title: "Ordinance"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: test2.qmd
        text: "Mapped Ordinances"
      - href: sources.qmd
        text: Selected Sources
      - about.qmd

format:
  html:
    theme:
      - minty
      - dark
    css: styles.css
    toc: true



