project:
  type: website

execute: 
  freeze: auto

website:
  title: "Ordinance"
  navbar:
    right:
      - href: index.qmd
        text: Home

      - text: "Mapped Ordinances"
        menu:
          - href: overview.qmd
            text: "Overview"
          - href: public-lands-1876.qmd
            text: "Public Lands Ordinance, 1876"
          - href: crown-lands-1894.qmd
            text: "Crown Lands Bill, 1894"
          - href: crown-lands-1897.qmd
            text: "Crown Lands Bill, 1897"
          - href: concessions-1900.qmd
            text: "Concessions Ordinance, 1900"
          - href: forest-bill-1910.qmd
            text: "Forest Bill, 1910"
          - href: forest-ordinance-1927.qmd
            text: "Forest Ordinance, 1927"
          - href: native-administration-jurisdiction.qmd
            text: "Native Administration Ordinances"
          - href: supreme-court.qmd
            text: "Supreme Court Ordinance"
      - href: achimota-legal-sequence.qmd
        text: Achimota
      - href: sources.qmd
        text: Selected Sources

      - href: about.qmd
        text: About
bibliography: reference.bib 

format:
  html:
    theme:
      - Minty
      - dark
    css: styles.css
    toc: true
  



